# Generated by Django 5.2.3 on 2025-06-29 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_order_cancel_reason_order_return_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancel_reason',
        ),
        migrations.RemoveField(
            model_name='order',
            name='return_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_returned',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
