# Generated by Django 5.2.3 on 2025-07-07 17:45

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '600x600', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=image_cropping.fields.ImageCropField(upload_to='products/'),
        ),
    ]
