# Generated by Django 5.2.3 on 2025-07-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_order_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='max_age',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum age in months (0-36)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_age',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum age in months (0-36)', null=True),
        ),
    ]
