# Generated by Django 5.2.3 on 2025-07-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_gender_product_max_age_product_min_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer_percentage',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
