# Generated by Django 5.2.3 on 2025-07-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_product_is_featured_product_is_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
