# Generated by Django 5.2.3 on 2025-08-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
