# Generated by Django 5.2.3 on 2025-07-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_wallet_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
    ]
