# Generated by Django 5.2.3 on 2025-07-08 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BabyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.CharField(blank=True, max_length=100, null=True)),
                ('baby_dob', models.DateField(blank=True, null=True)),
                ('baby_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True)),
                ('birth_weight', models.DecimalField(blank=True, decimal_places=1, help_text='kg (optional)', max_digits=4, null=True)),
                ('birth_height', models.DecimalField(blank=True, decimal_places=1, help_text='cm (optional)', max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, help_text='Special notes or health info (optional)', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
