# Generated by Django 5.2.3 on 2025-08-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_status_alter_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='times_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max times this coupon can be used', null=True),
        ),
    ]
